# Generated by Django 3.0.8 on 2020-07-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    # def generate_superuser(apps, schema_editor):
    #     from django.contrib.auth.models import User

    #     # DJANGO_DB_NAME = os.environ.get('DJANGO_DB_NAME', "default")
    #     DJANGO_SU_NAME = 'userdocker'
    #     DJANGO_SU_EMAIL = 'django@test.com'
    #     DJANGO_SU_PASSWORD = 'root'

    #     superuser = User.objects.create_superuser(
    #         username=DJANGO_SU_NAME,
    #         email=DJANGO_SU_EMAIL,
    #         password=DJANGO_SU_PASSWORD)

    #     superuser.save()
    operations = [
        # migrations.RunPython(generate_superuser),
        migrations.CreateModel(
            name='Peaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('altitude', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'peaks',
            },
        ),
    ]
