# Generated by Django 3.0.8 on 2020-07-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('altitude', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'peaks',
            },
        ),
    ]
